linters:
  enable:
    - unused
    - ineffassign
    - gofmt
    - goimports
    - govet
    - errcheck

linters-settings:
  unused:
    check-exported: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unused

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - simulator/target
